"""Public API coverage for review-before-load tabular imports."""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

import ring5

pytestmark = pytest.mark.public_api


def test_preview_is_non_mutating_and_loads_only_reviewed_rows(tmp_path: Path) -> None:
    # [test->req~ring5.ingestion.import-preview~1]
    source = tmp_path / "measurements.txt"
    source.write_text(
        "note generated by instrument\n"
        "benchmark|ipc|stable\n"
        "alpha|1.25|yes\n"
        "beta|not-a-number|no\n"
        "gamma|1.75|true\n",
        encoding="utf-8",
    )

    with ring5.Session() as session:
        preview = session.preview_import(
            str(source),
            header_row=2,
            column_types={"ipc": "number"},
            preview_rows=1,
        )
        assert session.api.state_manager.get_data() is None
        loaded = session.load_import(preview)

        pd.testing.assert_frame_equal(session.api.state_manager.get_data(), loaded)
        assert session.api.state_manager.get_csv_path() == str(source.resolve())
        assert session.api.state_manager.is_using_parser() is False

    assert isinstance(preview, ring5.ImportPreview)
    assert isinstance(preview.options, ring5.ImportOptions)
    assert isinstance(preview.columns[0], ring5.ImportColumn)
    assert isinstance(preview.rejected_rows[0], ring5.ImportRejectedRow)
    assert preview.delimiter == "|"
    assert preview.accepted_row_count == 2
    assert preview.rejected_row_count == 1
    assert preview.rejected_rows[0].line_number == 4
    assert list(loaded["benchmark"]) == ["alpha", "gamma"]
    assert list(loaded["ipc"]) == [1.25, 1.75]
    assert str(loaded["stable"].dtype) == "boolean"


def test_preview_failures_use_the_public_data_error(tmp_path: Path) -> None:
    source = tmp_path / "values.csv"
    source.write_text("value\n1\n", encoding="utf-8")

    with ring5.Session() as session:
        with pytest.raises(ring5.DataLoadError, match="header_row"):
            session.preview_import(str(source), header_row=0)
        with pytest.raises(ring5.DataLoadError, match="unknown columns"):
            session.preview_import(str(source), column_types={"missing": "integer"})

        preview = session.preview_import(str(source))
        source.write_text("value\n2\n", encoding="utf-8")
        with pytest.raises(ring5.DataLoadError, match="changed after preview"):
            session.load_import(preview)
