"""
RING-5 State Manager - Abstract Protocol & Public Exports.

Defines the AbstractStateManager protocol (Layer B contract) and re-exports
the concrete RepositoryStateManager for backward-compatible imports.

Architecture:
- AbstractStateManager: Protocol defining the state management interface
- RepositoryStateManager: Concrete implementation (lives in repository_state_manager.py)
"""

from typing import Any, Callable, Dict, List, Optional, Protocol, runtime_checkable

import pandas as pd

from src.core.domain.models import PortfolioData
from src.core.domain.plot_protocol import PlotProtocol

# Re-export concrete implementation so existing imports keep working:
#   from src.core.state.state_manager import RepositoryStateManager
from src.core.state.repository_state_manager import RepositoryStateManager as RepositoryStateManager


@runtime_checkable
class AbstractStateManager(Protocol):
    """
    Protocol defining the contract for State Management.
    Layer B (ApplicationAPI) depends on this protocol, not the implementation.
    """

    def initialize(self) -> None: ...

    # Data

    def get_data(self) -> Optional[pd.DataFrame]: ...

    def set_data(
        self, data: Optional[pd.DataFrame], on_change: Optional[Callable[[], None]] = None
    ) -> None: ...
    def get_processed_data(self) -> Optional[pd.DataFrame]: ...
    def set_processed_data(self, data: Optional[pd.DataFrame]) -> None: ...
    def has_data(self) -> bool: ...
    def clear_data(self) -> None: ...

    # Config
    def get_config(self) -> Dict[str, Any]: ...
    def set_config(self, config: Dict[str, Any]) -> None: ...
    def update_config(self, key: str, value: Any) -> None: ...
    def get_temp_dir(self) -> Optional[str]: ...
    def set_temp_dir(self, path: str) -> None: ...
    def get_csv_path(self) -> Optional[str]: ...
    def set_csv_path(self, path: str) -> None: ...
    def get_csv_pool(self) -> List[Dict[str, Any]]: ...
    def set_csv_pool(self, pool: List[Dict[str, Any]]) -> None: ...
    def get_saved_configs(self) -> List[Dict[str, Any]]: ...
    def set_saved_configs(self, configs: List[Dict[str, Any]]) -> None: ...

    # Parser
    def is_using_parser(self) -> bool: ...
    def set_use_parser(self, use: bool) -> None: ...
    def get_parse_variables(self) -> List[Dict[str, Any]]: ...
    def set_parse_variables(self, variables: List[Dict[str, Any]]) -> None: ...
    def get_stats_path(self) -> str: ...
    def set_stats_path(self, path: str) -> None: ...
    def get_stats_pattern(self) -> str: ...
    def set_stats_pattern(self, pattern: str) -> None: ...
    def get_scanned_variables(self) -> List[Dict[str, Any]]: ...
    def set_scanned_variables(self, variables: List[Dict[str, Any]]) -> None: ...
    def get_parser_strategy(self) -> str: ...
    def set_parser_strategy(self, strategy: str) -> None: ...

    # Plots
    def get_plots(self) -> List[PlotProtocol]: ...
    def set_plots(self, plots: List[PlotProtocol]) -> None: ...
    def add_plot(self, plot_obj: PlotProtocol) -> None: ...
    def get_plot_counter(self) -> int: ...
    def set_plot_counter(self, counter: int) -> None: ...
    def start_next_plot_id(self) -> int: ...
    def get_current_plot_id(self) -> Optional[int]: ...
    def set_current_plot_id(self, plot_id: Optional[int]) -> None: ...

    # Previews
    def set_preview(self, operation_name: str, data: pd.DataFrame) -> None: ...
    def get_preview(self, operation_name: str) -> Optional[pd.DataFrame]: ...
    def has_preview(self, operation_name: str) -> bool: ...
    def clear_preview(self, operation_name: str) -> None: ...

    # Session
    def clear_all(self) -> None: ...
    def restore_session(self, portfolio_data: PortfolioData) -> None: ...


# Backward compatibility alias
StateManager = RepositoryStateManager
