"""Tests for bounded, correction-aware tabular import previews."""

from __future__ import annotations

from pathlib import Path

import pytest

from src.core.models import ImportColumnCorrection, ImportOptions
from src.core.services.import_preview_service import ImportPreviewService


def _write_cp1252_table(path: Path) -> None:
    path.write_bytes(
        (
            "generated by instrument\n"
            "name;score;active;when\n"
            " alpha ;1.5;yes;2026-07-20\n"
            "café;bad;no;2026-07-21\n"
            "broken;2.0;true\n"
            "gamma;3.25;false;2026-07-22\n"
        ).encode("cp1252")
    )


def test_preview_detects_structure_types_and_explains_rejected_rows(tmp_path: Path) -> None:
    # [test->req~ring5.ingestion.import-preview~1]
    source = tmp_path / "instrument.csv"
    _write_cp1252_table(source)
    options = ImportOptions(
        header_row=2,
        column_types=(ImportColumnCorrection("score", "number"),),
        preview_rows=1,
    )

    preview = ImportPreviewService.preview(str(source), options)

    assert preview.encoding == "cp1252"
    assert preview.delimiter == ";"
    assert [column.name for column in preview.columns] == ["name", "score", "active", "when"]
    assert [column.inferred_type for column in preview.columns] == [
        "text",
        "text",
        "boolean",
        "datetime",
    ]
    assert preview.columns[1].import_as == "number"
    assert preview.accepted_row_count == 2
    assert preview.rejected_row_count == 2
    assert preview.total_row_count == 4
    assert preview.rows == (("alpha", "1.5", "true", "2026-07-20T00:00:00"),)
    assert preview.preview_truncated is True
    assert [row.line_number for row in preview.rejected_rows] == [4, 5]
    assert "expects number" in preview.rejected_rows[0].reason
    assert "Expected 4 fields" in preview.rejected_rows[1].reason


def test_load_uses_reviewed_types_and_refuses_changed_source(tmp_path: Path) -> None:
    source = tmp_path / "review.csv"
    source.write_text("id,value,enabled\n1,2.5,yes\n2,NA,no\n", encoding="utf-8")
    preview = ImportPreviewService.preview(str(source))

    frame = ImportPreviewService.load(preview)

    assert frame.to_dict("records") == [
        {"id": 1, "value": 2.5, "enabled": True},
        {"id": 2, "value": None, "enabled": False},
    ]
    assert str(frame["id"].dtype) == "Int64"
    assert str(frame["value"].dtype) == "Float64"
    assert str(frame["enabled"].dtype) == "boolean"

    source.write_text("id,value,enabled\n3,7.0,yes\n", encoding="utf-8")
    with pytest.raises(ValueError, match="changed after preview"):
        ImportPreviewService.load(preview)


@pytest.mark.parametrize(
    ("content", "message"),
    [
        ("a,a\n1,2\n", "duplicate"),
        ("a,,c\n1,2,3\n", "empty column"),
        ("metadata only\n", "header row 2"),
    ],
)
def test_invalid_headers_are_explicit(tmp_path: Path, content: str, message: str) -> None:
    source = tmp_path / "invalid.csv"
    source.write_text(content, encoding="utf-8")
    options = ImportOptions(header_row=2) if "row 2" in message else ImportOptions()

    with pytest.raises(ValueError, match=message):
        ImportPreviewService.preview(str(source), options)


def test_unknown_type_correction_is_rejected(tmp_path: Path) -> None:
    source = tmp_path / "values.csv"
    source.write_text("value\n1\n", encoding="utf-8")
    options = ImportOptions(column_types=(ImportColumnCorrection("missing", "integer"),))

    with pytest.raises(ValueError, match="unknown columns: missing"):
        ImportPreviewService.preview(str(source), options)


def test_delimiter_detection_respects_quoted_header_values(tmp_path: Path) -> None:
    source = tmp_path / "quoted-header.csv"
    source.write_text(
        '"benchmark, full name";score\n"alpha, tuned";1.5\n"beta, base";2.0\n',
        encoding="utf-8",
    )

    preview = ImportPreviewService.preview(str(source))

    assert preview.delimiter == ";"
    assert [column.name for column in preview.columns] == ["benchmark, full name", "score"]
    assert preview.accepted_row_count == 2
